const messages=[
  {cmd:'echo "you are my favorite notification"',text:'Anh không hứa sẽ làm mọi ngày đều hoàn hảo,<br><span>nhưng anh hứa sẽ làm chúng đáng nhớ hơn.</span>'},
  {cmd:'git commit -m "loving you, every day"',text:'Nếu cuộc đời là một dự án dài,<br><span>anh vẫn muốn chọn em làm phiên bản cuối cùng.</span>'},
  {cmd:'npm install happiness --save',text:'Mong em luôn cười thật nhiều,<br><span>vì nụ cười của em là giao diện anh thích nhất.</span>'},
  {cmd:'return "you are home"',text:'Dù ngày hôm nay có thế nào,<br><span>em vẫn luôn là nơi bình yên nhất của anh.</span>'}
];
const typed=document.getElementById('typedLine'), big=document.getElementById('bigMessage'), stage=document.getElementById('messageStage'); let current=0; let timer;
function typeMessage(index){current=index%messages.length; clearInterval(timer); const msg=messages[current]; typed.textContent='';big.style.opacity='0';let i=0;timer=setInterval(()=>{typed.textContent=msg.cmd.slice(0,++i);if(i>=msg.cmd.length){clearInterval(timer);setTimeout(()=>{big.innerHTML=msg.text;big.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:700,fill:'forwards',easing:'cubic-bezier(.2,.8,.2,1)'})},240)}},30)}
document.getElementById('startBtn').addEventListener('click',()=>{stage.scrollIntoView({behavior:'smooth'});typeMessage(0);startAudio(true)});
document.getElementById('anotherBtn').addEventListener('click',()=>typeMessage(current+1));
document.getElementById('replayBtn').addEventListener('click',()=>{window.scrollTo({top:0,behavior:'smooth'});typeMessage(0)});
const audio=document.getElementById('audio'), music=document.getElementById('musicBtn'), label=document.getElementById('musicLabel'), toast=document.getElementById('toast'); let audioStarted=false;
function startAudio(fromButton=false){if(audioStarted)return; audio.play().then(()=>{audioStarted=true;syncPlayer();burstHearts(8)}).catch(()=>{if(fromButton)showToast()})}
function showToast(){toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
const player=document.getElementById('player'),recordButton=document.getElementById('recordButton'),heartLayer=document.getElementById('heartLayer');function syncPlayer(){const playing=!audio.paused;music.classList.toggle('playing',playing);player.classList.toggle('playing',playing);label.textContent=playing?'đang phát':'bật nhạc'}function toggleAudio(){if(audio.paused){audio.play().then(()=>{audioStarted=true;syncPlayer();burstHearts(8)}).catch(showToast)}else{audio.pause();syncPlayer()}}music.addEventListener('click',toggleAudio);recordButton.addEventListener('click',toggleAudio);audio.addEventListener('play',syncPlayer);audio.addEventListener('pause',syncPlayer);
function burstHearts(count=5,x=innerWidth*.5){for(let i=0;i<count;i++){const heart=document.createElement('span');heart.className='floating-heart';heart.textContent=Math.random()>.22?'♡':'♥';heart.style.left=`${Math.max(3,Math.min(97,x/innerWidth*100+(Math.random()-.5)*8))}%`;heart.style.setProperty('--size',`${12+Math.random()*18}px`);heart.style.setProperty('--duration',`${3.8+Math.random()*2.4}s`);heart.style.setProperty('--drift',`${(Math.random()-.5)*180}px`);heart.style.setProperty('--rotate',`${(Math.random()-.5)*40}deg`);heartLayer.appendChild(heart);heart.addEventListener('animationend',()=>heart.remove(),{once:true})}}
addEventListener('pointerdown',e=>{if(e.target.closest('button,.player'))burstHearts(3,e.clientX)},{passive:true});
const canvas=document.getElementById('particles'),ctx=canvas.getContext('2d',{alpha:true});let dots=[],mouse={x:-1000,y:-1000},raf=0,visible=true;function resize(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const count=innerWidth<700?16:34;dots=Array.from({length:count},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.35+.35,vx:(Math.random()-.5)*.12,vy:(Math.random()-.5)*.12,a:Math.random()*.35+.08}))}function draw(){if(!visible){raf=0;return}ctx.clearRect(0,0,innerWidth,innerHeight);for(const d of dots){const dx=d.x-mouse.x,dy=d.y-mouse.y,dist=Math.hypot(dx,dy);if(dist<130&&dist>0){d.x+=dx/dist*.22;d.y+=dy/dist*.22}d.x+=d.vx;d.y+=d.vy;if(d.x<0)d.x=innerWidth;if(d.x>innerWidth)d.x=0;if(d.y<0)d.y=innerHeight;if(d.y>innerHeight)d.y=0;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fillStyle=`rgba(245,166,187,${d.a})`;ctx.fill()}raf=requestAnimationFrame(draw)}addEventListener('resize',resize,{passive:true});addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY},{passive:true});document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible&&!raf)raf=requestAnimationFrame(draw)});resize();raf=requestAnimationFrame(draw);

const progress=document.getElementById('scrollProgress'), floatWords=[...document.querySelectorAll('.float-word')], titleLines=[...document.querySelectorAll('.title-line')], reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let ticking=false;function onScroll(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`;if(!reduceMotion){const q=document.querySelector('.kinetic-quote'),r=q.getBoundingClientRect(),p=(innerHeight-r.top)/(innerHeight+r.height);if(p>=0&&p<=1){floatWords[0].style.transform=`translate3d(${p*9}vw,${p*55}px,0)`;floatWords[1].style.transform=`translate3d(${-p*8}vw,${-p*40}px,0)`;floatWords[2].style.transform=`translate3d(${p*4}vw,${-p*70}px,0)`}}ticking=false})}addEventListener('scroll',onScroll,{passive:true});onScroll();
if(!reduceMotion&&matchMedia('(pointer:fine)').matches){document.getElementById('heroTitle').addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;titleLines.forEach((line,i)=>line.style.transform=`translate3d(${x*(i+1)*8}px,${y*(i+1)*5}px,0)`)});document.getElementById('heroTitle').addEventListener('pointerleave',()=>titleLines.forEach(l=>l.style.transform=''));document.querySelectorAll('.wish-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty('--card-x',`${x*100}%`);card.style.setProperty('--card-y',`${y*100}%`);card.style.transform=`perspective(700px) rotateX(${(y-.5)*-6}deg) rotateY(${(x-.5)*7}deg) translateY(-6px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
